### ISSUE TITLE
Used to work perfectly but not now

### ISSUE THREAD

**Issue by Tripp3235** [wrjlewis/notion-search-alfred-workflow#29]
**Describe the bug**
Not sure what happened, everything has been fine for months but this week when I try to perform an Alfred search it always comes back stating it finds no results.  

**Workflow (please complete the following information):**
 - Version from July 2020

**Additional context**
Attempted to try to recreate cookie and Space ID headers.  Unfortunately when logging into Notion on the website I can no longer find my space ID (perhaps that is the problem).  Tried using browsers Firefox and Safari.

**Comment by wrjlewis** [comment]
Can you see the space id in the request payload as seen in the image linked in the Readme? https://github.com/wrjlewis/notion-search-alfred-workflow/raw/master/spaceId.png

**Comment by Tripp3235** [comment]
So I downloaded and installed Chrome and it shows up like your image so hopefully I can get back on track now.  I'll see if readding those items tonight will get my workflow searching again.  I've really missed it.

**Comment by Tripp3235** [comment]
Ok, so I got my cookie and spaceID.  It's still not working.  It used to.  It keep saying "No Results - Go To Notion Homepage."

**Comment by frufru666** [comment]
I have the same issue unfortunately.

**Comment by wrjlewis** [comment]
Since Notion doesn't have a proper API it makes it very difficult to debug, there are no errors returned on failure currently. The only thing I can suggest is logging out of Notion, logging back in again to Notion, copying the cookie over (you shouldn't need to update the space id because it stays the same), and trying again. 
If there is anything else that could be helpful to know, that might help debug, please do share.

**Comment by Tripp3235** [comment]
Thank you, that did fix it.  Wanted to let you know.
