### ISSUE TITLE
Workflow error

### ISSUE THREAD

**Issue by pattard** [wrjlewis/notion-search-alfred-workflow#30]
I've been using this workflow for over a year now and it's been great, thank you for sharing it. However, it is now no longer working for me.

**Describe the bug**
Whenever I initiate the search I receive the following error.

<img width="296" alt="Screenshot 2021-06-03 at 11 58 53" src="https://user-images.githubusercontent.com/1904782/120626821-56ae4500-c463-11eb-9a3e-a9cc2e917244.png">

I've tried to logout and back in to Notion, restarted my computer, updated the variables.

The Error log shows the following:
```
panic: unable to open database file: operation not permitted

goroutine 1 [running]:
main.PanicOnErr(...)
	/Users/sean/Dropbox (MIT)/Dotfiles/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C13422B2-62E5-4A91-A8D9-65E18FA46712/search/main.go:406
main.main()
	/Users/sean/Dropbox (MIT)/Dotfiles/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C13422B2-62E5-4A91-A8D9-65E18FA46712/search/main.go:420 +0x636
panic: unable to open database file: operation not permitted
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Type 'ns`

**Workflow (please complete the following information):**
 - Version 0.3.3

**Comment by wrjlewis** [comment]
Hey

Although I'm not certain, I suspect this error is caused by a permissions issue. Usually you see this error if the application (in this case Alfred) has not been granted full disk access in Security & Privacy > Privacy tab > 'Full Disk Access' secion. 

Have you recently changed your installation of Alfred at all, or maybe upgraded your mac version before you started seeing these errors? 

Thanks.

**Comment by pattard** [comment]
@wrjlewis thank you for that quick response. You were correct. The weird thing is that I hadn't updated anything on my system and no other application was re-requesting access.

Thanks for your help.
