### ISSUE TITLE
Alfred 3 compatibility?

### ISSUE THREAD

**Issue by bradydjohnson** [wrjlewis/notion-search-alfred-workflow#6]
Are you using any of the new Alfred 4 elements? I have Alfred 3, and it says it's not compatible. :(
<img width="606" alt="Alfred Preferences 2020-05-08 13-44-57" src="https://user-images.githubusercontent.com/6741590/81438278-1d0cec80-9132-11ea-9aa4-8a41fdae9dfa.png">

**Comment by wrjlewis** [comment]
Hi.

Did a bit of digging on this. 

For workflows to be compatible with v3, they need to be created in v3. If they're created in v4, even if they're not using Alfred 4 elements, they won't be compatible with v3. 

Since I made this workflow in v4 (I only have v4), it's not compatible with v3. 

Someone will need to create this app in v3 for it to be compatible. 

[See this thread](https://www.alfredforum.com/topic/13041-i-created-the-workflow-in-alfred4-and-exported-it/) for more detail, if someone comes across this and wants to port it to v3. Should be fairly trivial. 

Thanks

**Comment by bradydjohnson** [comment]
Thanks for your help. Really appreciate it.
