### ISSUE TITLE
Notion app does not launch since update

### ISSUE THREAD

**Issue by Feivel65** [wrjlewis/notion-search-alfred-workflow#75]
Since updating to the Alfred 5 version of this workflow the notion Mac app does not launch anymore when hitting enter on a result. 
Only time it does still work is if the app is not yet launched. A really annoying bug, I miss the functionality multiple times a day and would be very grateful for a fix.

Kindest regards and thanks for your work

**Comment by wrjlewis** [comment]
Interesting! Especially because that part of the code wasn't changed in the upgrade. Could be something to do with Alfred 5 though and how it handles opening external apps. 
If you try downloading and installing the Alfred4 version of the workflow (link the readme), do you still have the same problem?

**Comment by Feivel65** [comment]
@wrjlewis weirdly enough it doesn't! I feel like the v4 Workflow worked in my v5 Alfred before I first updated to the v5 workflow, though…

**Comment by wrjlewis** [comment]
Ah ok, thanks, we're getting somewhere then.. 
If you remove the notion workflow you have installed in Alfred. You can install the v4 version of the workflow (from the readme it lists both downloads) as it is backwards compatible. If the v4 version of the workflow works with Alfred v5 then we know the problem is in the workflow rather than in the Alfred app (or at least we can investigate that possibility further).

**Comment by danielgsanz** [comment]
Same here! I've just installed both versions, and it opens the web version. I'm also having the following error `Open Notion - No results, empty query, or error` Do you know how to solve it?

**Comment by wrjlewis** [comment]
@danielgsanz are you changing the use desktop client option, in order to open the desktop client rather than the web app?

Re no results, I would suggest re-acquiring and copy/pasting your cookie and space id, this usually fixes the issue

**Comment by danielgsanz** [comment]
Hi @wrjlewis changing `useDesktopClient` to True and adding `token_v2=` prefix to cookie value solve the issue. Thanks a lot, great job!!
