### ISSUE TITLE
No result display and show back

### ISSUE THREAD

**Issue by robinyujiang** [wrjlewis/notion-search-alfred-workflow#76]
[15:14:46.398] Logging Started...
[15:14:49.237] Notion Search[Script Filter] Queuing argument ''
[15:14:52.429] Notion Search[Script Filter] Script with argv '(null)' finished
[15:14:52.434] Notion Search[Script Filter] {"items": [{"uid": 1, "type": "default", "title": "There was an error:", "subtitle": "245: [Errno 9] Bad file descriptor", "arg": "https://www.notion.so/"}]}

**Comment by wrjlewis** [comment]
That's strange, not sure I've seen a bad file descriptor error here before.
Just to check, have you tried reacquiring both the cookie and space Id, and re put them in?

**Comment by danielgsanz** [comment]
Hi @robinyujiang I've the same issue and I solved it adding `token_v2=` prefix to cookie value :) I hope it also works for you

**Comment by wrjlewis** [comment]
Thanks @danielgsanz 

That's interesting, because I expect folk to copy the whole cookie, which includes many lines and includes the token_v2= in there. 
Would you mind taking a screenshot (and covering up any sensitive info like the token_v2 value) of where you're retrieving the cookie?

This will help me update the instructions as needed. Thanks again and glad it's working!

**Comment by robinyujiang** [comment]
@danielgsanz Thanks for the solution. I tried the solution and ... Yes, it works! Thanks!

**Comment by wrjlewis** [comment]
@robinyujiang @danielgsanz 
Can I ask what browser you are using, is it Safari? 

Thanks!

**Comment by danielgsanz** [comment]
@wrjlewis I used Firefox :)

**Comment by robinyujiang** [comment]
@wrjlewis I use Chrome.

**Comment by wrjlewis** [comment]
Thanks both, I’ll make sure the instructions are up to date 👍
